### ISSUE TITLE
Website Version 1 Feature Roadmap

### ISSUE THREAD

**Issue by TheCedarPrince** [Julia-Streamers/StreamerSite#7]
## Overview

For the Julia Streamers Website, we want to keep it very simple, clean, and straightforward to use for a Version 1 release. Essentially, the flow of a user experience on the site would be this:

1. User enters website
2. User sees brief description about the Julia/Julia Streamers community
3. User sees landing screen with a table of active Twitch users
4. User sees in the table, what the topic of the stream is
5. User can click name of streamer to go to streamer's stream

## Roadmap

To better solidify the goals for the creation of the website, here is the tentative road map to a Version 1 release:

- [x] Determine best method about who is online [see #2 #6]
- [x] Create logo for website [see #4]
- [x] Pick or create theme for Franklin deployment [see #3]
- [x] Structure backend of website appropriately [see #5]
- [x] Deployment to GitHub pages [see #9]
- [ ] Detail how streamers add themselves to the website [see #16] 
- [ ] Improve on critiques [see #15]
- [ ] Create website content

## Conclusion

Thanks all for the help to make this project a reality! We are making great progress. If you think of anything else needed for a Version 1 release, please let us know and we can see about adding it to the road map. Keep rocking on! :guitar:
